version: '3'

services:
  database:
    image: postgres
    restart: always

    ports:
      - '5432:5432'

    environment:
      POSTGRES_PASSWORD: db_password

  backend:
    build: .
    depends_on:
      - database

    volumes:
      - './:/app'
      - '/app/node_modules'

    ports:
      - '3000:3000'

    env_file:
      - .env
